FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
# FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS build

WORKDIR /app

COPY . .

EXPOSE 8080

RUN dotnet build WebAPI20230803.csproj -c Release
RUN dotnet publish WebAPI20230803.csproj -c Release -o /app/publish /p:self-contained=true
# --os linux --arch x64

## Distroless 베이스 이미지를 사용하여 최종 이미지 빌드
# FROM gcr.io/distroless/dotnet-7.0-sdk
# FROM gcr.io/distroless/dotnet-7.0-runtime
# FROM asia.gcr.io/distroless/dotnet-7.0
FROM gcr.io/distroless/cc
# FROM gcr.io/distroless/base
# FROM gcr.io/distroless/base-nossl

COPY --from=build /app/publish /app

# ENTRYPOINT ["dotnet", "run", "--project", "WebAPI20230803.csproj"]
# ENTRYPOINT ["dotnet", "WebAPI20230803.dll"]
ENTRYPOINT ["/app/WebAPI20230803"]
# CMD ["/app/WebAPI20230803"]

#############################################

## .NET SDK 이미지를 사용하여 애플리케이션 빌드
#FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
#WORKDIR /src
#EXPOSE 8080
#
## 소스 코드 복사
#COPY . .
#
## RUN dotnet build -c Release
#RUN dotnet build /src/WebAPI20230803.csproj -c Release -o /app/build /p:self-contained=true
## --os linux --arch x64
#
## 프로젝트 publish
#RUN dotnet publish /src/WebAPI20230803.csproj -c Release -o /app/publish /p:self-contained=true
## --os linux --arch x64
#
## Distroless 베이스 이미지를 사용하여 최종 이미지 빌드
## FROM gcr.io/distroless/base
#FROM gcr.io/distroless/cc
## FROM gcr.io/distroless/static
## FROM gcr.io/distroless/dotnet/core/aspnet:3.1
## FROM gcr.io/distroless/dotnet/core/aspnet:debug
## FROM gcr.io/distroless/dotnet:latest
#WORKDIR /app/publish
#COPY --from=build /app/publish .
#
## 애플리케이션 실행
## ENTRYPOINT ["dotnet", "WebAPI20230803.dll"]
#CMD ["/app/publish/WebAPI20230803"]

#############################################

## .NET SDK를 사용하여 앱 빌드
#FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
#WORKDIR /app
#
## 소스 코드 복사
#COPY . .
#
## 앱 빌드
#RUN dotnet publish -c Release -o out
## /p:self-contained=true
#
## Distroless 베이스 이미지를 사용하여 최종 이미지 생성
#FROM gcr.io/distroless/cc
## FROM gcr.io/distroless/base
## FROM gcr.io/distroless/dotnet:latest
## FROM gcr.io/distroless/dotnet/core/aspnet:3.1
## FROM gcr.io/distroless/dotnet/core/aspnet:debug
#WORKDIR /app
#COPY --from=build /app/out .
#
#ENTRYPOINT ["dotnet", "WebAPI20230803.dll"]
## ENTRYPOINT ["./WebAPI20230803"]

#############################################

## FROM gcr.io/distroless/base
#FROM gcr.io/distroless/dotnet/core/aspnet:3.1
## RUN apk add bash
## && apt-get update && apt-get install -y dotnet-sdk-6.0
#
#WORKDIR /app
#
## dotnet build 명령을 사용하여 앱을 빌드합니다.
#RUN dotnet build WebAPI20230803.csproj
## -c Release
## -o bin/
#
## dotnet publish 명령을 사용하여 앱을 배포합니다.
#RUN dotnet publish WebAPI20230803.csproj
## -c Release
## -o bin/ -r linux-x64
#
#COPY ./bin/Debug/net7.0 /app
#
## CMD ["/app/WebAPI20230803"]
#
#ENTRYPOINT ["dotnet", "WebAPI20230803.dll"]

#############################################

## 베이스 이미지 설정
#FROM gcr.io/distroless/base AS base
#
#RUN apt-get update && apt-get install -y dotnet-sdk-7.0
#
#WORKDIR /app
#EXPOSE 8080
#
## 빌드 이미지 설정
## FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
## RUN apk add --no-cache dotnet-sdk-7.0
#
#
#WORKDIR /src
#COPY ["WebAPI20230803.csproj", "."]
#RUN dotnet restore "./WebAPI20230803.csproj"
#COPY . .
#WORKDIR "/src/."
#RUN dotnet build "WebAPI20230803.csproj" -c Release -o /app/build
## -r alpine.3.6-x64
#
#FROM build AS publish
#RUN dotnet publish "WebAPI20230803.csproj" -c Release -o /app/publish
## --os linux --arch x64
## /p:UseAppHost=false
## /p:self-contained=true
#
#FROM build AS final
#ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
#ENV TZ=Asia/Seoul
#USER root
#
#WORKDIR /app
#COPY --from=publish /app/publish .
#ENTRYPOINT ["dotnet", "WebAPI20230803.dll"]